# Generated by Django 4.2.7 on 2023-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AddField(
            model_name='guide',
            name='company_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
